name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'master'
        channel: 'master'

    - name: Install dependencies
      run: flutter pub get
      working-directory: simple_app
    
    - name: Analyze code
      run: flutter analyze
      working-directory: simple_app

    - name: Run tests
      run: flutter test
      working-directory: simple_app
